### ISSUE TITLE
bug: Input with decimals doesn't work

### ISSUE THREAD

**Issue by FJLendinez** [rare-magma/guitos#43]
# Bug Report

**guitos version:**
EUR
[v0.12.0](https://github.com/rare-magma/guitos/blob/main/CHANGELOG.md)

**Current behavior:**

On each input text, I tried to input decimals, for example, 123,45. If I use it with ",", is accepted but not computed. With "." doesn't let me write.

I tried to export, edit the json and import and then the numbers are shown and computed correctly.

**Expected behavior:**

When someone write "," or ".", it should accept decimals.
 
**Steps to reproduce:**

 Write 123,45 on the value of expenses or revenue

**Related code:**

I suppose that the bug is in the parsing of numbers, like here more or less. https://github.com/rare-magma/guitos/blob/main/src/components/ItemForm/ItemFormGroup.tsx#L38

**Comment by rare-magma** [comment]
thanks for taking the time to write a comprehensive bug report @FJLendinez !
I'm able to reproduce the issue if I configure my browser to use the Spanish locale but not when I have it set to English (Ireland).
guitos uses https://github.com/cchanxzy/react-currency-input-field/ to format the income/expense value input.
This input receives the browser's locale and the aforementioned library uses it to format the display value accordingly.

Unfortunately it seems like it's caused by a bug in it, see:
https://github.com/cchanxzy/react-currency-input-field/issues/232
https://github.com/cchanxzy/react-currency-input-field/issues/206

Some locales use "." as a decimal separator instead of a comma as per https://en.wikipedia.org/wiki/Decimal_separator so this could perhaps explain why the library doesn't allow using , or . depending on which locale is selected.
I'll investigate the code responsible for this (https://github.com/cchanxzy/react-currency-input-field/blob/master/src/components/utils/getLocaleConfig.ts) and let you know if I can figure out a way to solve the problem.
Cheers!

**Comment by rare-magma** [comment]
I guess there's a workaround, we could parse the localized number that is input in the expenses/income value and normalize it to save in the DB by using https://github.com/globalizejs/globalize/blob/master/doc/api/number/number-parser.md
I'll give it a shot and let you know.

**Comment by rare-magma** [comment]
@FJLendinez I think there were actually 2 different issues that caused your problem:
1. your browser locale is not set to Spanish or some other locale that uses commas as decimal separators
   - if this is true, then the https://github.com/cchanxzy/react-currency-input-field/ will refuse to use commas as decimal separators. In order to solve this problem I'd suggest changing the browser locale to one that uses commas as decimal separators.
2. guitos was trying to save the expense/income value to the browser database "as is" so in the case that the value had a comma decimal separator, it would refuse to do so since it couldn't parse a number correctly. 
    - I've fixed this problem by taking into account the user's locale when doing this operation (see: https://github.com/rare-magma/guitos/commit/ea63d1f8e171fd41d5e4179ce35b3f93773d720c)

Please update your app by refreshing the page and let me know if the issue persists.

**Comment by FJLendinez** [comment]
Thanks for your response and the speed of solving the issue. I tried it right now using the version 0.12.2 and it works successfully.

**Comment by rare-magma** [comment]
Thanks for confirming, I'm glad the problem is fixed! 
I'll proceed with closing the issue.
